export type Locale = "en" | "fr";
export type Project = {
  slug: string;
  title: Record<Locale, string>;
  description: Record<Locale, string>;
  category: Record<Locale, string>;
  year: string;
  mediaType: "photo" | "video";
  coverImage: string;
  alt: Record<Locale, string>;
  featured: boolean;
  published: boolean;
  displayOrder: number;
  aspect: "wide" | "portrait" | "square";
  position?: string;
};

export const projects: Project[] = [
  { slug: "midnight-velocity", title: { en: "Midnight Velocity", fr: "Vélocité Nocturne" }, description: { en: "A nocturnal automotive study shaped by rain, reflection and the rhythm of the city.", fr: "Une étude automobile nocturne façonnée par la pluie, les reflets et le rythme de la ville." }, category: { en: "Automotive", fr: "Automobile" }, year: "2026", mediaType: "photo", coverImage: "/media/midnight-velocity.png", alt: { en: "Dark sports coupe on a rain-lit Paris street", fr: "Coupé sombre sur une avenue parisienne éclairée par la pluie" }, featured: true, published: true, displayOrder: 1, aspect: "wide" },
  { slug: "crafted-for-motion", title: { en: "Crafted for Motion", fr: "Conçu pour le Mouvement" }, description: { en: "Precision, surface and speed distilled into a concise moving-image campaign.", fr: "Précision, matière et vitesse réunies dans une campagne filmée concise." }, category: { en: "Personalised Ads", fr: "Publicité sur mesure" }, year: "2026", mediaType: "video", coverImage: "/media/midnight-velocity.png", alt: { en: "Cinematic rear view of a sports coupe at night", fr: "Vue arrière cinématographique d’un coupé sportif de nuit" }, featured: true, published: true, displayOrder: 2, aspect: "portrait", position: "72% center" },
  { slug: "paris-after-light", title: { en: "Paris After Light", fr: "Paris Après la Lumière" }, description: { en: "Quiet fragments of the capital held between daylight and night.", fr: "Fragments silencieux de la capitale, suspendus entre le jour et la nuit." }, category: { en: "City Study", fr: "Étude urbaine" }, year: "2025", mediaType: "photo", coverImage: "/media/a-day-to-remember.png", alt: { en: "Warm Paris apartment seen through an evening window", fr: "Appartement parisien chaleureux vu à travers une fenêtre le soir" }, featured: true, published: true, displayOrder: 3, aspect: "square", position: "left center" },
  { slug: "quiet-character", title: { en: "Quiet Character", fr: "Caractère Discret" }, description: { en: "A portrait series about presence, restraint and honest gestures.", fr: "Une série de portraits sur la présence, la retenue et la sincérité des gestes." }, category: { en: "Portraits", fr: "Portraits" }, year: "2025", mediaType: "photo", coverImage: "/media/quiet-character.png", alt: { en: "South Asian creative professional beside a Paris atelier window", fr: "Créative sud-asiatique près de la fenêtre d’un atelier parisien" }, featured: true, published: true, displayOrder: 4, aspect: "portrait" },
  { slug: "atelier-no-7", title: { en: "Atelier No. 7", fr: "Atelier N° 7" }, description: { en: "A tactile short-form study created for an independent fragrance atelier.", fr: "Une étude tactile au format court, créée pour un atelier de parfumerie indépendant." }, category: { en: "Personalised Ads", fr: "Publicité sur mesure" }, year: "2026", mediaType: "video", coverImage: "/media/atelier-no-7.png", alt: { en: "Amber perfume bottle in sculptural warm light", fr: "Flacon de parfum ambré dans une lumière chaude et sculpturale" }, featured: true, published: true, displayOrder: 5, aspect: "wide" },
  { slug: "a-day-to-remember", title: { en: "A Day to Remember", fr: "Un Jour à Retenir" }, description: { en: "Unscripted details from a private celebration, observed with warmth and discretion.", fr: "Les détails spontanés d’une célébration privée, observés avec chaleur et discrétion." }, category: { en: "Small Events", fr: "Événements intimes" }, year: "2025", mediaType: "photo", coverImage: "/media/a-day-to-remember.png", alt: { en: "Guests raising glasses at an intimate Paris dinner", fr: "Des invités lèvent leur verre lors d’un dîner intime à Paris" }, featured: true, published: true, displayOrder: 6, aspect: "wide" },
  { slug: "urban-pulse", title: { en: "Urban Pulse", fr: "Pulsation Urbaine" }, description: { en: "A film-led exploration of machines moving through the city after dark.", fr: "Une exploration filmée des machines en mouvement dans la ville après la nuit." }, category: { en: "Automotive", fr: "Automobile" }, year: "2025", mediaType: "video", coverImage: "/media/midnight-velocity.png", alt: { en: "Night reflections around a moving sports coupe", fr: "Reflets nocturnes autour d’un coupé sportif en mouvement" }, featured: false, published: true, displayOrder: 7, aspect: "square", position: "40% center" },
  { slug: "driven-by-detail", title: { en: "Driven by Detail", fr: "Le Sens du Détail" }, description: { en: "A close visual language built from form, material and controlled light.", fr: "Un langage visuel rapproché, composé de formes, de matières et de lumière maîtrisée." }, category: { en: "Creative Direction", fr: "Direction créative" }, year: "2026", mediaType: "photo", coverImage: "/media/atelier-no-7.png", alt: { en: "Minimal amber bottle and botanical still life", fr: "Nature morte minimale avec flacon ambré et végétal" }, featured: false, published: true, displayOrder: 8, aspect: "portrait", position: "65% center" },
];

export const copy = {
  en: {
    nav: { home: "Home", about: "About", gallery: "Gallery", contact: "Contact", talk: "Let’s talk", menu: "Menu", close: "Close menu" },
    heroKicker: "Independent visual studio · Paris",
    heroTitle: { lead: "Stories framed with", accent: "motion and light." },
    heroText: "Photography and films by Athulkrishna, capturing people, machines and meaningful moments from Paris and beyond.",
    viewWork: "View selected work", contactWhatsApp: "Start a conversation", featuredEyebrow: "Selected work", featuredTitle: "Images with atmosphere. Films with pulse.",
    servicesEyebrow: "Services", servicesTitle: "From a single frame to a moving story.", services: [["01", "Photography", "Portrait, automotive, brand and intimate event imagery."], ["02", "Videography", "Cinematic short films with a natural sense of movement."], ["03", "Creative direction", "Visual concepts shaped around your subject and audience."], ["04", "Short-form content", "Distinctive social and campaign assets made to travel well."]],
    aboutEyebrow: "Behind AX7MOV", aboutTitle: "Observed carefully. Made to feel alive.", aboutPreview: "Athulkrishna is a photographer and filmmaker drawn to the small gestures, changing light and considered details that give a story its character.", readStory: "Read the story",
    instagramTitle: "Selected from Instagram.", instagramText: "A changing edit of recent frames and moving-image experiments.", visitInstagram: "Visit @ax7.mov", instagramPlaceholder: "Selected posts will appear here",
    closing: "Have a story in mind?", closingSub: "Tell me where it begins.",
    footerLine: "Cinematic photography and films from Paris and beyond.",
    galleryEyebrow: "Photography + film", galleryTitle: "Selected work, without boundaries.", galleryIntro: "An ongoing collection across people, machines, brand stories and private moments.", openProject: "Open project", closeViewer: "Close viewer", previous: "Previous project", next: "Next project",
    aboutPageEyebrow: "Athulkrishna · Photographer + filmmaker", aboutPageTitle: "Authentic moments, composed with intent.", bio: "Athulkrishna is the photographer and filmmaker behind AX7MOV, an independent visual studio based in Paris. With more than two years of experience, he creates cinematic photography and films across automotive, portrait, personalised advertising and intimate event work. His approach combines careful composition, natural movement and atmospheric storytelling to produce images that feel polished without losing their authenticity. Available for projects in Paris and for selected work that requires travel.", approach: "I work close to the subject, leaving enough room for real gestures and unexpected light. Every commission begins with listening, then finding the visual rhythm that belongs to it.", facts: [["Based", "Paris, France"], ["Experience", "2+ years"], ["Available", "Local + selected travel"], ["Practice", "Photography + videography"]], pricing: "Pricing is tailored to each project’s scope, production needs and travel distance.",
    contactEyebrow: "Start a conversation", contactTitle: "Tell me what you want to make.", contactIntro: "Tell me about your idea, location, preferred dates and the kind of photography or film you need.", whatsapp: "Message on WhatsApp", email: "Send an email", call: "Call", details: "Useful details to include", detailItems: ["Your idea or brief", "Location and preferred dates", "Photography, film, or both", "Intended use and timing"], serviceArea: "Based in Paris and available for selected travel assignments. Pricing depends on project requirements and travel distance.",
    studioTitle: "AX7MOV Content Studio", studioText: "Portfolio content is managed in Sanity. Add your project ID to connect this site, then open the hosted Sanity Studio to edit projects, Instagram selections and site settings.", studioOpen: "Open Sanity Studio", studioSetup: "CMS setup instructions",
  },
  fr: {
    nav: { home: "Accueil", about: "À propos", gallery: "Galerie", contact: "Contact", talk: "Parlons-en", menu: "Menu", close: "Fermer le menu" },
    heroKicker: "Studio visuel indépendant · Paris",
    heroTitle: { lead: "Des histoires cadrées par", accent: "le mouvement et la lumière." },
    heroText: "Photographies et films d’Athulkrishna, pour saisir les personnes, les machines et les instants qui comptent, à Paris et ailleurs.",
    viewWork: "Voir la sélection", contactWhatsApp: "Démarrer une conversation", featuredEyebrow: "Travaux sélectionnés", featuredTitle: "Des images habitées. Des films en mouvement.",
    servicesEyebrow: "Services", servicesTitle: "D’une image unique à une histoire en mouvement.", services: [["01", "Photographie", "Portrait, automobile, marque et événements intimes."], ["02", "Vidéo", "Des films cinématographiques courts au mouvement naturel."], ["03", "Direction créative", "Des concepts visuels pensés pour votre sujet et votre public."], ["04", "Contenu court", "Des créations distinctives pour les réseaux et les campagnes."]],
    aboutEyebrow: "Derrière AX7MOV", aboutTitle: "Observer avec attention. Donner vie aux images.", aboutPreview: "Photographe et réalisateur, Athulkrishna s’intéresse aux gestes discrets, aux variations de lumière et aux détails qui donnent son caractère à une histoire.", readStory: "Découvrir son parcours",
    instagramTitle: "Sélection Instagram.", instagramText: "Une sélection évolutive de photographies récentes et d’expérimentations filmées.", visitInstagram: "Voir @ax7.mov", instagramPlaceholder: "Les publications sélectionnées apparaîtront ici",
    closing: "Une histoire en tête ?", closingSub: "Racontez-moi où elle commence.",
    footerLine: "Photographies et films cinématographiques, à Paris et ailleurs.",
    galleryEyebrow: "Photographie + film", galleryTitle: "Une sélection sans frontières.", galleryIntro: "Une collection en mouvement, entre personnes, machines, récits de marque et moments privés.", openProject: "Ouvrir le projet", closeViewer: "Fermer", previous: "Projet précédent", next: "Projet suivant",
    aboutPageEyebrow: "Athulkrishna · Photographe + réalisateur", aboutPageTitle: "Des moments vrais, composés avec intention.", bio: "Athulkrishna est le photographe et réalisateur à l’origine d’AX7MOV, un studio visuel indépendant installé à Paris. Fort de plus de deux ans d’expérience, il imagine des photographies et des films cinématographiques pour l’automobile, le portrait, la publicité sur mesure et les événements intimistes. Son regard associe une composition précise, un mouvement naturel et un sens de l’atmosphère pour créer des images soignées qui restent profondément authentiques. Il travaille à Paris et se déplace pour certains projets.", approach: "Je travaille au plus près du sujet, tout en laissant une place aux gestes spontanés et à la lumière inattendue. Chaque projet commence par l’écoute, puis par la recherche du rythme visuel qui lui est propre.", facts: [["Basé à", "Paris, France"], ["Expérience", "Plus de 2 ans"], ["Disponible", "Paris + déplacements"], ["Pratique", "Photographie + vidéo"]], pricing: "Les tarifs sont établis selon l’ampleur du projet, les besoins de production et la distance de déplacement.",
    contactEyebrow: "Démarrer une conversation", contactTitle: "Parlez-moi de ce que vous imaginez.", contactIntro: "Présentez-moi votre idée, le lieu, les dates souhaitées et le type de photographie ou de film dont vous avez besoin.", whatsapp: "Écrire sur WhatsApp", email: "Envoyer un e-mail", call: "Appeler", details: "Informations utiles", detailItems: ["Votre idée ou votre brief", "Le lieu et les dates souhaitées", "Photo, film, ou les deux", "L’usage prévu et le calendrier"], serviceArea: "Basé à Paris et disponible pour certains projets nécessitant un déplacement. Les tarifs dépendent des besoins du projet et de la distance.",
    studioTitle: "Studio de contenu AX7MOV", studioText: "Les contenus du portfolio sont gérés avec Sanity. Ajoutez l’identifiant du projet pour connecter le site, puis ouvrez Sanity Studio pour modifier les projets, la sélection Instagram et les réglages du site.", studioOpen: "Ouvrir Sanity Studio", studioSetup: "Instructions de configuration",
  },
} as const;
